(ns turing_machine.common_functions_test
  	(:use [clojure.test])
	(:use [turing_machine.core])
	(:use [turing_machine.tape])
	(:use [turing_machine.console])
	(:use [turing_machine.common_functions])
)

(deftest should_generate_move_m_configs
	(is (re-matches #"^l_[\.|\d]+ \| ANY \| L \| config_1$" (:m_config (l "config_1"))))
	(is (re-matches #"^l_[\.|\d]+$" (:config_name (l "config_1"))))
	(is (re-matches #"^r_[\.|\d]+ \| ANY \| R \| config_2$" (:m_config (r "config_2"))))
	(is (re-matches #"^r_[\.|\d]+$" (:config_name (r "config_2"))))

	(def machine_description (:m_config (r "config_1")))
	(def tape (create_tape))
	(println machine_description)
	(def complete_config_after_execution (execute_machine_with_tape machine_description 5 tape))

	(def tape_after_execution (:tape complete_config_after_execution))
	(def machine_after_execution (:machine complete_config_after_execution))
	
	(is (= 1 (:cursor machine_after_execution)))
)

(deftest should_generate_erase_m_configs
	; TODO: describe expected m_configs generated by e here
)

(deftest should_generate_find_m_configs
	; TODO: describe expected m_configs generated by f here
)
