(ns turing_machine.common_functions_test
  	(:use [clojure.test])
	(:use [turing_machine.common_functions])
)

(deftest should_generate_move_m_configs
	(is (= "l | ANY | L | config_1" (l "config_1")))
	(is (= "r | ANY | R | config_1" (r "config_1")))
)

(deftest should_generate_find_m_configs
	; TODO: describe expected m_configs generated by f here
)